# Generated by Django 3.2.6 on 2021-08-14 03:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(choices=[('admin', 'Admin'), ('reader', 'Reader')], max_length=30, verbose_name='Entity')),
                ('name', models.CharField(max_length=50, verbose_name='Access Name')),
                ('type', models.CharField(max_length=100, verbose_name='Access type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Access',
                'verbose_name_plural': 'Accesses',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('reader', 'Reader')], max_length=50, verbose_name='Role Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('access', models.ManyToManyField(blank=True, related_name='role_access', to='base.Access')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
