# Generated by Django 3.2.6 on 2021-08-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='entity',
        ),
    ]
