# Generated by Django 3.2.6 on 2021-08-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_access_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Role Name'),
        ),
    ]
